version: "0.5"
is_strict: true
processes:
  init_dependencies:
    namespace: init
    command: |
      pnpm install
  dev:
    namespace: dev
    command: |
      SHELL=/bin/bash pnpm dev
    depends_on:
      init_dependencies:
        condition: process_completed_successfully
