version: "0.5"
is_strict: true
disable_env_expansion: true
processes:
  init_dependencies:
    namespace: init
    command: |
      pnpm install
  init_dev_project:
    namespace: init
    command: |
      CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}"
      DEV_PROJECT_ID_FILE="$CONFIG_DIR/loopback/dev-project-id.txt"

      if [ ! -f "$DEV_PROJECT_ID_FILE" ]; then
          echo "Warning: Config file not found at $DEV_PROJECT_ID_FILE"
          echo "Use Cmd+K in the local Loopback dashboard to set the current project as the dev project locally"
          exit 0
      fi

      echo "Reading dev project ID from: $DEV_PROJECT_ID_FILE"
      PROJECT_ID=$(cat "$DEV_PROJECT_ID_FILE")
      echo "Setting the project ID $PROJECT_ID in local files..."
      echo "  packages/widget-js-script/index.html"
      sed -i -E "s/data-project-id=\"[^\"]*\"/data-project-id=\"$PROJECT_ID\"/" packages/widget-js-script/index.html
      echo "  packages/widget-svelte/src/routes/+page.svelte"
      sed -i -E "s/<Widget projectId=\"[^\"]*\"/<Widget projectId=\"$PROJECT_ID\"/" packages/widget-svelte/src/routes/+page.svelte
      echo "Done"
  dev:
    namespace: dev
    command: |
      SHELL=/bin/bash pnpm dev
    depends_on:
      init_dependencies:
        condition: process_completed_successfully
